### ISSUE TITLE
Decide whether to use YAML format instead for alf config

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [DannyBen/alf#51]
My primary wish is to enable intellisence here. ;)

**Comment by DannyBen** [comment]
Yeah... I don't see this happening. For three primary reasons:

1. There is no real YAML parsing in bash, since there are no nested hashes in bash. At best, there is some simple awkward parsing like I did in the [built in YAML library in bashly](https://github.com/DannyBen/bashly/blob/master/lib/bashly/libraries/yaml/yaml.sh).
2. Alf wants to give each alias both a string value, and possible key-value children pairs.
3. There is no real advantage for choosing YAML as a format, except for forcing it into a schema.

This alf config

```yaml
g: git
  b: branch
  d: diff --unified=0
  co: checkout
```

Would look like this in YAML:

```yaml
g:
  command: git
  subcommands:
    b: branch
    d: diff --unified=0
    co: checkout
```

which is too verbose.

I imagine [my personal alf-conf](https://github.com/DannyBen/alf-conf/blob/master/alf.conf) would get quite clunky with such a change.

The inspiration for alf config (and [opcode](https://github.com/DannyBen/opcode)) came from [Procfile syntax](https://devcenter.heroku.com/articles/procfile#procfile-format)

**Comment by EmilyGraceSeville7cf** [comment]
> There is no real YAML parsing in bash, since there are no nested hashes in bash. At best, there is some simple awkward parsing like I did in the [built in YAML library in bashly](https://github.com/DannyBen/bashly/blob/master/lib/bashly/libraries/yaml/yaml.sh)

What about [yq](https://mikefarah.gitbook.io/yq/) tool? It suits for JSON parsing too, but not just that.

> Would look like this in YAML:

Or like this:

```yaml
g:
  git:
    b: branch
    d: diff --unified=0
    co: checkout
```

**Comment by DannyBen** [comment]
> What about [yq](https://mikefarah.gitbook.io/yq/) tool?

It adds a dependency, and is more suitable for interacting with single values.



> Or like this:
> 
> ```yaml
> g:
>   git:
>     b: branch
>     d: diff --unified=0
>     co: checkout
> ```

No. The command needs to be a value, not a key, as it is allowed to get complex:

```yaml
dns: if [[ -n "$2" ]]; then host -t $2 $1; else host $1; fi
  flush: !sudo systemd-resolve --flush-caches
  stats: !sudo systemd-resolve --statistics
  --flush: !dns flush && dns
  help: !echo -e "Usage:\n  dns example.com\n  dns example.com mx\n  dns --flush example.com\n  dns flush\n  dns stats"
```
